[workspace]

members = [
    "cli_projects/cli_app",
    "progress_bar",
    "drop_trait",
    "custom_iterator",
    "tcp_server_client",
    "rustcat",
    "libp2p",
    "cli_projects/recho",
    "cli_projects/rls",
    "cli_projects/todo",
    "cli_projects/todo_2",
    "macros",
    "random1",
    "custom_vec",
]
