[package]
name = "scylla_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
lazy_static = { version = "1.4.0" }
scylla = "0.11.0"
tokio = "1.36.0"
