version: '3.8'

services:
  scylla:
    image: scylladb/scylla:latest
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla

  scylla_db:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - scylla
    environment:
      - SCYLLA_HOST=scylla

volumes:
  scylla_data:
